[mavlink]
device = "/dev/ttyAMA2"
baud = 115200
mav_version = 2

[drops]
cruise_speed = 20
wind_speed = 0
wind_direction = 0
altitude = 60

[drops.beacon]
mass = 155
cd = 0.27
drop_course = 0
x_translation = -61.11344194743686
y_translation = 0.0

[drops.bottle]
mass = 255
cd = 0.3
drop_course = 0
x_translation = -60.47685254127766
y_translation = 0.0

[camera]
resolution = [
    1920,
    1080,
]

[dirs]
logs_dir = "media/logs"
photos_dir = "media/photos"
videos_dir = "media/videos"
zones_dir = "configuration/zones"

[system]
debug_mode = false

[zones]
search_zone_path = "Sloszowa_target_detection_1.poly"
